//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsyncGuiApp.QuestionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QuestionService.IQuestionService")]
    public interface IQuestionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionService/GetQuote", ReplyAction="http://tempuri.org/IQuestionService/GetQuoteResponse")]
        string GetQuote();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionService/GetQuote", ReplyAction="http://tempuri.org/IQuestionService/GetQuoteResponse")]
        System.Threading.Tasks.Task<string> GetQuoteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionService/AskDeepThought", ReplyAction="http://tempuri.org/IQuestionService/AskDeepThoughtResponse")]
        int AskDeepThought();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuestionService/AskDeepThought", ReplyAction="http://tempuri.org/IQuestionService/AskDeepThoughtResponse")]
        System.Threading.Tasks.Task<int> AskDeepThoughtAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQuestionServiceChannel : AsyncGuiApp.QuestionService.IQuestionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuestionServiceClient : System.ServiceModel.ClientBase<AsyncGuiApp.QuestionService.IQuestionService>, AsyncGuiApp.QuestionService.IQuestionService {
        
        public QuestionServiceClient() {
        }
        
        public QuestionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QuestionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuestionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuestionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetQuote() {
            return base.Channel.GetQuote();
        }
        
        public System.Threading.Tasks.Task<string> GetQuoteAsync() {
            return base.Channel.GetQuoteAsync();
        }
        
        public int AskDeepThought() {
            return base.Channel.AskDeepThought();
        }
        
        public System.Threading.Tasks.Task<int> AskDeepThoughtAsync() {
            return base.Channel.AskDeepThoughtAsync();
        }
    }
}
