//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsyncGuiApp.CompositeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CompositeService.ICompositeService")]
    public interface ICompositeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompositeService/GetQuotes", ReplyAction="http://tempuri.org/ICompositeService/GetQuotesResponse")]
        System.Collections.Generic.List<string> GetQuotes(int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompositeService/GetQuotes", ReplyAction="http://tempuri.org/ICompositeService/GetQuotesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetQuotesAsync(int count);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICompositeServiceChannel : AsyncGuiApp.CompositeService.ICompositeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompositeServiceClient : System.ServiceModel.ClientBase<AsyncGuiApp.CompositeService.ICompositeService>, AsyncGuiApp.CompositeService.ICompositeService {
        
        public CompositeServiceClient() {
        }
        
        public CompositeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompositeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompositeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompositeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<string> GetQuotes(int count) {
            return base.Channel.GetQuotes(count);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetQuotesAsync(int count) {
            return base.Channel.GetQuotesAsync(count);
        }
    }
}
